/*ORGANIZACIONES*/


INSERT INTO ORGANIZACION VALUES ('1', 'AFC');
INSERT INTO ORGANIZACION VALUES ('2', 'CAF');
INSERT INTO ORGANIZACION VALUES ('3', 'CONCACAF');
INSERT INTO ORGANIZACION VALUES ('4', 'CONMEBOL');
INSERT INTO ORGANIZACION VALUES ('5', 'OFC');
INSERT INTO ORGANIZACION VALUES ('6', 'UEFA');



/* ARBITROS*/

INSERT INTO ARBITRO VALUES ('1', '7', '1', 'Fahad', 'AL MIRDASI');
INSERT INTO ARBITRO VALUES ('2', '13', '1', 'Alireza', 'FAGHANI');
INSERT INTO ARBITRO VALUES ('3', '108', '1', 'Ravshan', 'IRMATOV');
INSERT INTO ARBITRO VALUES ('4', '109', '1', 'Mohammed Abdulla', 'MOHAMED');
INSERT INTO ARBITRO VALUES ('5', '35', '1', 'Ryuji', 'SATO');
INSERT INTO ARBITRO VALUES ('6', '110', '1', 'Nawaf Abdulla', 'SHUKRALLA');
INSERT INTO ARBITRO VALUES ('7', '111', '3', 'Joel', 'AGUILAR');
INSERT INTO ARBITRO VALUES ('8', '112', '3', 'Mark W.', 'GEIGER');
INSERT INTO ARBITRO VALUES ('9', '112', '3', 'Jair', 'MARRUFO');
INSERT INTO ARBITRO VALUES ('10', '24', '3', 'Ricardo', 'MONTERO');
INSERT INTO ARBITRO VALUES ('11', '31', '3', 'John', 'PITTI');
INSERT INTO ARBITRO VALUES ('12', '27', '3', 'Cesar Arturo', 'RAMOS PALAZUELOS');
INSERT INTO ARBITRO VALUES ('13', '113', '4', 'Julio', 'BASCUÑAN');
INSERT INTO ARBITRO VALUES ('14', '114', '4', 'Enrique', 'CACERES');
INSERT INTO ARBITRO VALUES ('15', '9', '4', 'Andres', 'CUNHA');
INSERT INTO ARBITRO VALUES ('16', '18', '4', 'Nestor', 'PITANA');
INSERT INTO ARBITRO VALUES ('17', '22', '4', 'Sandro', 'RICCI');
INSERT INTO ARBITRO VALUES ('18', '36', '4', 'Wilmar', 'ROLDAN');
INSERT INTO ARBITRO VALUES ('19', '115', '2', 'Mehdi', 'ABID CHAREF');
INSERT INTO ARBITRO VALUES ('20', '37', '2', 'Malang', 'DIEDHIOU');
INSERT INTO ARBITRO VALUES ('21', '116', '2', 'Bakary Papa', 'GASSAMA');
INSERT INTO ARBITRO VALUES ('22', '8', '2', 'Ghead', 'GRISHA');
INSERT INTO ARBITRO VALUES ('23', '117', '2', 'Janny', 'SIKAZWE');
INSERT INTO ARBITRO VALUES ('24', '118', '2', 'Bamlak', 'TESSEMA WEYESA');
INSERT INTO ARBITRO VALUES ('25', '119', '5', 'Matthew', 'CONGER');
INSERT INTO ARBITRO VALUES ('26', '120', '5', 'Norbert', 'HAUATA');
INSERT INTO ARBITRO VALUES ('27', '27', '6', 'Felix', 'BRYCH');
INSERT INTO ARBITRO VALUES ('28', '121', '6', 'Cuneyt', 'CAKIR');
INSERT INTO ARBITRO VALUES ('29', '6', '6', 'Sergey', 'KARASEV');
INSERT INTO ARBITRO VALUES ('30', '22', '6', 'Bjorn', 'KUIPERS');
INSERT INTO ARBITRO VALUES ('31', '34', '6', 'Szymon', 'MARCINIAK');
INSERT INTO ARBITRO VALUES ('32', '11', '6', 'Antonio Miguel', 'MATEU LAHOZ');
INSERT INTO ARBITRO VALUES ('33', '25', '6', 'Milorad', 'MAZIC');
INSERT INTO ARBITRO VALUES ('34', '123', '6', 'Gianluca', 'ROCCHI');
INSERT INTO ARBITRO VALUES ('35', '124', '6', 'Damir', 'SKOMINA');
INSERT INTO ARBITRO VALUES ('36', '14', '6', 'Clement', 'TURPIN');
