INSERT INTO GRUPO VALUES('A','GRUPO A');
INSERT INTO GRUPO VALUES('B','GRUPO B');
INSERT INTO GRUPO VALUES('C','GRUPO C');
INSERT INTO GRUPO VALUES('D','GRUPO D');
INSERT INTO GRUPO VALUES('E','GRUPO E');
INSERT INTO GRUPO VALUES('F','GRUPO F');
INSERT INTO GRUPO VALUES('G','GRUPO G');
INSERT INTO GRUPO VALUES('H','GRUPO H');
