INSERT INTO Grupo VALUES('A','GRUPO A');
INSERT INTO Grupo VALUES('B','GRUPO B');
INSERT INTO Grupo VALUES('C','GRUPO C');
INSERT INTO Grupo VALUES('D','GRUPO D');
INSERT INTO Grupo VALUES('E','GRUPO E');
INSERT INTO Grupo VALUES('F','GRUPO F');
INSERT INTO Grupo VALUES('G','GRUPO G');
INSERT INTO Grupo VALUES('H','GRUPO H');