INSERT INTO grupo VALUES('A','GRUPO A');
INSERT INTO grupo VALUES('B','GRUPO B');
INSERT INTO grupo VALUES('C','GRUPO C');
INSERT INTO grupo VALUES('D','GRUPO D');
INSERT INTO grupo VALUES('E','GRUPO E');
INSERT INTO grupo VALUES('F','GRUPO F');
INSERT INTO grupo VALUES('G','GRUPO G');
INSERT INTO grupo VALUES('H','GRUPO H');