INSERT INTO LUGAR VALUES ('62', '4', '38');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '62', 'Estadio Olímpico Luzhnikí');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '62', '31/07/1956');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '62', '81500');

INSERT INTO LUGAR VALUES ('63', '4', '39');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');

INSERT INTO LUGAR VALUES ('', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('1', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('5', '', '');
INSERT INTO OBSERVACIONLUGAR VALUES ('6', '', '');
